### PR TITLE
Optionally set widths for tabswap labels

### PR DESCRIPTION
**Pull request by yutakahoulette-zz**

### CODE REVIEW

**Comment by yutakahoulette** [comment]
added an optional option for tabSwap label function for setting label widths (like wizard labels).

**Comment by jayrbolton** [comment]
This PR looks great. Would it be possible to just set a percentage width into a data-ff-* attribute, and then CSS can use that with the `attr()` function?

**Comment by yutakahoulette** [comment]
i'm pretty certain that you can only use attr data for the content css
rule, but i double check mañana.

**Comment by jayrbolton** [comment]
Oh ya that's definitely true, I forgot about that.

**Pull request merged**
